### ISSUE TITLE
Looking for a mantainer of this project

### ISSUE THREAD

**Issue by hdoro** [hdoro/stencil-realworld-app#8]
As I have no more interest in Stencil, it's a disservice to the community having this repository under my ownership.

If anyone has an appetite for maintaining this code base and loves working with Stencil, reach out for us to go through the transfer.

@khaledosman  @anishkny, as you've already contributed (thanks for that, btw!), you have the priority here. Any thoughts? 😄

**Comment by khaledosman** [comment]
Sure, I would love to maintain the project

**Comment by hdoro** [comment]
Thank you, Khaled!

I just need you to close or rename your fork of this repo, then. Otherwise Github won't let me transfer it to you :)

**Comment by khaledosman** [comment]
Done

**Comment by hdoro** [comment]
There we go! Just accept the invite and it'll be done, thank you for this, Khaled 😄

**Comment by khaledosman** [comment]
@hdoro thanks, is there anything I need to do to setup deployments? or should I do a new netlify setup and update the readme with the new link?

**Comment by hdoro** [comment]
Hm... that's true! Transfers in Netlify are a bit of a pain, so I think your suggestion is the best bet.

The only thing to bear in mind is:
- build command: `npm run build`
- publish directory: `www`

I renamed the current Netlify website in case you want to keep the `stencil-realworld.netlify.app` URL 😉

**Comment by khaledosman** [comment]
I'll switch to that then, thanks!
